### PR TITLE
Add base WYSIWYG title styles and add the options to the base WYSIWYG options. Resolves #51.

### LINKED ISSUE #51: WYSIWYG title classes in base settings.
## Lewis Collard

> WYSIWYG title classes in base settings.

Good idea. Plus stub classes in the WYSIWYG CSS?

WYSIWYG editor idea: can we make the default background colour in the admin white?

### PR DESCRIPTION
**Pull request by danielsamuels**

### CODE REVIEW

**Comment by lewiscollard** [comment]
+1 from here.

**Comment by danielsamuels** [comment]
@dan-gamble: Would you want those commented out `@apply`s in the template?

**Comment by dan-gamble** [comment]
I think the commented out things are actually okay to leave, otherwise people can easily skim over them classes and think they've been added fine. Might even be worth adding more to it to let people know they still need to be updated

**Comment by danielsamuels** [comment]
Leaving it as-is for now, we can always update the defaults in future.

**Pull request merged**
