### PR TITLE
Avoid opening mailto: links in a new window

### PR DESCRIPTION
**Pull request by danielsamuels**

### CODE REVIEW

**Comment by lewiscollard** [comment]
What happens if their default mail handler is set to a webmail service (something I would not expect to be uncommon)?

Also out of curiosity, what happens if they have a program assigned to mailto links? A blank tab?

**Comment by danielsamuels** [comment]
> What happens if their default mail handler is set to a webmail service (something I would not expect to be uncommon)?

Is that even possible?

> Also out of curiosity, what happens if they have a program assigned to mailto links? A blank tab?

Yeah, you basically get `about:blank` in a new tab.

**Comment by danielsamuels** [comment]
Ok so it is possible and the answer is that you get gmail in your current tab.

**Comment by lewiscollard** [comment]
In that case I think the more common case - i.e. probably ALL mobile devices, plus people on desktop with real mail clients installed - should be optimised. So this works for me.

**Review by lewiscollard — APPROVED** [review]

**Pull request merged**
