### PR TITLE
Add support for events app. Resolves #50.

### LINKED ISSUE #50: Events app (LCFI)

### PR DESCRIPTION
**Pull request by danielsamuels**

### CODE REVIEW

**Comment by lewiscollard** [comment]
Should I suggest tweaks to the events app here or over in the cms-events repo?

**Comment by danielsamuels** [comment]
Over there

**Comment by danielsamuels** [comment]
I don't think adding _support_ for the app is too controversial, so unless anyone has any objections, I'm going to merge this one in.

**Comment by lewiscollard** [comment]
No objections!

**Pull request merged**
