### PR TITLE
Order settings by their name.

### PR DESCRIPTION
**Pull request by lewiscollard**
Right now they come out in primary key order, which is not very obvious behaviour.

### CODE REVIEW

**Review by danielsamuels — APPROVED** [review]

**Comment by danielsamuels** [comment]
Either add a migration, or update the base one.

**Comment by lewiscollard** [comment]
As we're starting to do with the other apps, can we start off with an empty (minus `__init__.py`) migrations folder instead?

**Comment by danielsamuels** [comment]
WFM

**Comment by lewiscollard** [comment]
Tada!

**Comment by danielsamuels** [comment]
Nice.

**Pull request merged**
