### PR TITLE
Fixes for #146, #148, #149

### PR DESCRIPTION
**Pull request by dan-gamble**
`stylelint --fix` is a tad spotty with our `property-definitions.css`. I've [raised an issue](https://github.com/stylelint/stylelint/issues/2643) so hopefully that's sorted soon and that could be added in.

Even though the `stylelint --fix` stuff is spotty i think this is fine to merge as we have the `prettier` part working fine 👍

### CODE REVIEW

**Comment by danielsamuels** [comment]
What's the max line length set to? It seems pretty narrow.

**Comment by dan-gamble** [comment]
[80](https://github.com/prettier/prettier#options) They recommend to not go over it. Baring in mind this doesn't impact how we write JS, just the way we read it i figured it was fine.

We can still write lines 150 long if we want, they will just get formatted down to 80 on commit.

**Comment by danielsamuels** [comment]
It's just when I see lines like this:

```
    const currentPos =
       window.scrollY || window.pageYOffset || document.documentElement.scrollTop
```

It just seems like a bit of a pointless wrap, if anything I would say it's less readable than just having it on one line.  I see what they mean about the reasoning behind not increasing it, you definitely wouldn't want all lines at 100, 120 or w/e.  I dunno, I guess I just don't like the feeling that it makes _some_ code look worse.

**Comment by dan-gamble** [comment]
If it's really causing some problems on certain lines you could just add `// prettier-ignore`. If it becomes a wider problem we could potentially look at other avenues.

**Review by danielsamuels — APPROVED** [review]

**Pull request merged**
