### PR TITLE
Add babel-preset-env and babel-preset-latest

### LINKED ISSUE #83: Use "latest" babel preset instead of yearlys
https://babeljs.io/docs/plugins/preset-latest/

### PR DESCRIPTION
**Pull request by dan-gamble**
Updates some core babel plugins too
Also update autoprefixer's browser list

Fixes #83

### CODE REVIEW

**Comment by dan-gamble** [comment]
It's worth holding off until https://github.com/babel/babel-preset-env/pull/56 gets merged as this look's like a big addition

**Comment by dan-gamble** [comment]
This has been released now: https://github.com/babel/babel-preset-env/releases/tag/v1.0.0

**Comment by danielsamuels** [comment]
You've got a conflict here.

**Comment by dan-gamble** [comment]
Yea, i'm also not sure how to get it working. Might take another look on the weekend

**Pull request merged**
